### ISSUE TITLE
Booster meta data belongs into catalog

### ISSUE THREAD

**Issue by heiko-braun** [openshiftio/launchpad-backend#67]
Currently the booster meta data resides with each booster, but from my point of view it belongs into the catalog:

```
name: HTTP CRUD - Wildfly Swarm
description: A simple CRUD application using Wildfly Swarm
versions:
  - id: community
    name: 2017.9.5 (Community)
  - id: redhat
    name: 7.0.0.redhat-6 (RHOAR)
```

All of the above has to kept redundantly in the each booster branch (community/prod) while it's  really an overarching concern. I suggest we move this data into the catalog, rather then keeping it with each booster.
